### PR TITLE
Make script work for both python2.7 and 3.6

### PR DESCRIPTION
**Pull request by vteratipally**
Signed-off-by: Varsha Teratipally teratipally@google.com

### CODE REVIEW

**Comment by vteratipally** [comment]
I have tested this by creating a gce instance with config and the containerd and docker services are running properly now.

**Comment by Random-Liu** [comment]
The change is used to fix Kubernetes upstream containerd test.

The script change is GCE only and has been tested. I think it looks good to me.

/lgtm

**Review by estesp — APPROVED** [review]
LGTM

**Pull request merged**
