### PR TITLE
Ignore temporary permission denied error.

### PR DESCRIPTION
**Pull request by Random-Liu**
Fixes https://github.com/containerd/cri/issues/1288.

The current windows ssh setup can't avoid the occasional "permission denied" error, because it have to periodically update the ssh key file with the latest ssh keys from GCP. To avoid flaky test, let's retry on the "Permission Denied" error.

Signed-off-by: Lantao Liu <lantaol@google.com>

### CODE REVIEW

**Comment by Random-Liu** [comment]
@mikebrow What do you mean?

**Comment by Random-Liu** [comment]
> Suggest passing in the duration value as well as the number of iterations.

I made the retry number to be fixed inside the retry helper. Not sure whether that was what you mean, but I do think it is cleaner.

**Comment by mikebrow** [comment]
> @mikebrow What do you mean?
```
function retry_on_error() {
	  local -r MAX_ATTEMPTS="$1"
	  local -r ON_ERROR="$2"
+        local -r SLEEP_DURATION="$3" 

...

	    sleep SLEEP_DURATION

```

**Comment by Random-Liu** [comment]
The latest run still failed after 10 times retry:
```
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
+ ((  attempts++  ))
+ [[ -n Permission denied ]]
+ grep 'Permission denied' /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
+ ((  attempts > MAX_ATTEMPTS  ))
+ log 'gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...'
++ date
+ echo 'Mon Sep 23 19:01:18 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...'
Mon Sep 23 19:01:18 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...
+ sleep 1
+ gcloud compute scp --recurse 'windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/*' /logs/artifacts
+ cat /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
+ ((  attempts++  ))
+ [[ -n Permission denied ]]
+ grep 'Permission denied' /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
+ ((  attempts > MAX_ATTEMPTS  ))
+ log 'gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...'
++ date
+ echo 'Mon Sep 23 19:01:21 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...'
Mon Sep 23 19:01:21 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...
+ sleep 1
+ gcloud compute scp --recurse 'windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/*' /logs/artifacts
+ cat /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
+ ((  attempts++  ))
+ [[ -n Permission denied ]]
+ grep 'Permission denied' /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
+ ((  attempts > MAX_ATTEMPTS  ))
+ log 'gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...'
++ date
+ echo 'Mon Sep 23 19:01:24 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...'
Mon Sep 23 19:01:24 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...
+ sleep 1
+ gcloud compute scp --recurse 'windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/*' /logs/artifacts
+ cat /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
+ ((  attempts++  ))
+ [[ -n Permission denied ]]
+ grep 'Permission denied' /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
+ ((  attempts > MAX_ATTEMPTS  ))
+ log 'gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...'
++ date
+ echo 'Mon Sep 23 19:01:26 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...'
Mon Sep 23 19:01:26 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...
+ sleep 1
+ gcloud compute scp --recurse 'windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/*' /logs/artifacts
+ cat /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
+ ((  attempts++  ))
+ [[ -n Permission denied ]]
+ grep 'Permission denied' /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
+ ((  attempts > MAX_ATTEMPTS  ))
+ log 'gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...'
++ date
+ echo 'Mon Sep 23 19:01:29 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...'
Mon Sep 23 19:01:29 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...
+ sleep 1
+ gcloud compute scp --recurse 'windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/*' /logs/artifacts
+ cat /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
+ ((  attempts++  ))
+ [[ -n Permission denied ]]
+ grep 'Permission denied' /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
+ ((  attempts > MAX_ATTEMPTS  ))
+ log 'gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...'
++ date
+ echo 'Mon Sep 23 19:01:31 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...'
Mon Sep 23 19:01:31 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...
+ sleep 1
+ gcloud compute scp --recurse 'windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/*' /logs/artifacts
+ cat /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
+ ((  attempts++  ))
+ [[ -n Permission denied ]]
+ grep 'Permission denied' /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
+ ((  attempts > MAX_ATTEMPTS  ))
+ log 'gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...'
++ date
+ echo 'Mon Sep 23 19:01:34 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...'
Mon Sep 23 19:01:34 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...
+ sleep 1
+ gcloud compute scp --recurse 'windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/*' /logs/artifacts
+ cat /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
+ ((  attempts++  ))
+ [[ -n Permission denied ]]
+ grep 'Permission denied' /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
+ ((  attempts > MAX_ATTEMPTS  ))
+ log 'gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...'
++ date
+ echo 'Mon Sep 23 19:01:37 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...'
Mon Sep 23 19:01:37 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...
+ sleep 1
+ gcloud compute scp --recurse 'windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/*' /logs/artifacts
+ cat /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
+ ((  attempts++  ))
+ [[ -n Permission denied ]]
+ grep 'Permission denied' /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
+ ((  attempts > MAX_ATTEMPTS  ))
+ log 'gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...'
++ date
+ echo 'Mon Sep 23 19:01:39 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...'
Mon Sep 23 19:01:39 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, retry in 1 second...
+ sleep 1
+ gcloud compute scp --recurse 'windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/*' /logs/artifacts
+ cat /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
+ ((  attempts++  ))
+ [[ -n Permission denied ]]
+ grep 'Permission denied' /tmp/tmp.pdNhIfQ66u/tmp.lIHT1A6CII
+ ((  attempts > MAX_ATTEMPTS  ))
+ log 'gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, 10 retry exceeded!'
++ date
+ echo 'Mon Sep 23 19:01:42 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, 10 retry exceeded!'
Mon Sep 23 19:01:42 UTC 2019 gcloud compute scp --recurse windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d:C:/_artifacts/* /logs/artifacts failed, 10 retry exceeded!
+ exit 1
+ cleanup
+ rm -rf /tmp/tmp.pdNhIfQ66u
+ [[ true == \t\r\u\e ]]
+ log 'Delete the test instance'
++ date
+ echo 'Mon Sep 23 19:01:42 UTC 2019 Delete the test instance'
Mon Sep 23 19:01:42 UTC 2019 Delete the test instance
+ gcloud compute instances delete -q windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d
Deleted [https://www.googleapis.com/compute/v1/projects/cri-containerd-node-e2e/zones/us-west1-b/instances/windows-cri-a69a8fea-28eb-4014-bcd9-4816a729457d].
+ EXIT_VALUE=1
+ set +o xtrace
```

I'll extend the retry period to 1min, if it still doesn't work, we need to debug more why this happens... :(

**Comment by mikebrow** [comment]
> The latest run still failed after 10 times retry:

do you need to do that scp with root@?

**Comment by Random-Liu** [comment]
The retry seems to be working now with longer period of wait:
```
ssh ready
+ rm /tmp/tmp.dOV272Gf8r/tmp.4oPKuyad0K
+ log 'Setup test environment in the test instance'
++ date
+ echo 'Mon Sep 23 21:20:10 UTC 2019 Setup test environment in the test instance'
Mon Sep 23 21:20:10 UTC 2019 Setup test environment in the test instance
+ retry_on_permission_error gcloud compute scp /home/prow/go/src/github.com/containerd/cri/test/windows/../../test/windows/setup-vm.ps1 windows-cri-9942ff8e-e44c-4bde-b98c-ed1b6acb624d:C:/setup-vm.ps1
+ retry_on_error 12 5 'Permission denied' gcloud compute scp /home/prow/go/src/github.com/containerd/cri/test/windows/../../test/windows/setup-vm.ps1 windows-cri-9942ff8e-e44c-4bde-b98c-ed1b6acb624d:C:/setup-vm.ps1
+ local -r MAX_ATTEMPTS=12
+ local -r SLEEP_PERIOD=5
+ local -r 'ON_ERROR=Permission denied'
+ shift 3
+ local attempts=1
++ mktemp -p /tmp/tmp.dOV272Gf8r
+ local -r stderr=/tmp/tmp.dOV272Gf8r/tmp.6WD6LBp9nu
+ gcloud compute scp /home/prow/go/src/github.com/containerd/cri/test/windows/../../test/windows/setup-vm.ps1 windows-cri-9942ff8e-e44c-4bde-b98c-ed1b6acb624d:C:/setup-vm.ps1
+ cat /tmp/tmp.dOV272Gf8r/tmp.6WD6LBp9nu
Permission denied (publickey,keyboard-interactive).
lost connection
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
+ ((  attempts++  ))
+ [[ -n Permission denied ]]
+ grep 'Permission denied' /tmp/tmp.dOV272Gf8r/tmp.6WD6LBp9nu
+ ((  attempts > MAX_ATTEMPTS  ))
+ log 'gcloud compute scp /home/prow/go/src/github.com/containerd/cri/test/windows/../../test/windows/setup-vm.ps1 windows-cri-9942ff8e-e44c-4bde-b98c-ed1b6acb624d:C:/setup-vm.ps1 failed, retry in 5 second...'
++ date
+ echo 'Mon Sep 23 21:20:12 UTC 2019 gcloud compute scp /home/prow/go/src/github.com/containerd/cri/test/windows/../../test/windows/setup-vm.ps1 windows-cri-9942ff8e-e44c-4bde-b98c-ed1b6acb624d:C:/setup-vm.ps1 failed, retry in 5 second...'
Mon Sep 23 21:20:12 UTC 2019 gcloud compute scp /home/prow/go/src/github.com/containerd/cri/test/windows/../../test/windows/setup-vm.ps1 windows-cri-9942ff8e-e44c-4bde-b98c-ed1b6acb624d:C:/setup-vm.ps1 failed, retry in 5 second...
+ sleep 5
+ gcloud compute scp /home/prow/go/src/github.com/containerd/cri/test/windows/../../test/windows/setup-vm.ps1 windows-cri-9942ff8e-e44c-4bde-b98c-ed1b6acb624d:C:/setup-vm.ps1
+ rm /tmp/tmp.dOV272Gf8r/tmp.6WD6LBp9nu
+ retry_on_permission_error gcloud compute ssh windows-cri-9942ff8e-e44c-4bde-b98c-ed1b6acb624d '--command=powershell /c C:/setup-vm.ps1'
+ retry_on_error 12 5 'Permission denied' gcloud compute ssh windows-cri-9942ff8e-e44c-4bde-b98c-ed1b6acb624d '--command=powershell /c C:/setup-vm.ps1'
+ local -r MAX_ATTEMPTS=12
+ local -r SLEEP_PERIOD=5
+ local -r 'ON_ERROR=Permission denied'
+ shift 3
+ local attempts=1
++ mktemp -p /tmp/tmp.dOV272Gf8r
+ local -r stderr=/tmp/tmp.dOV272Gf8r/tmp.eRqo6PX1wQ
```

**Pull request merged**
