### PR TITLE
Return gRPC errors from instrumentedService

### PR DESCRIPTION
**Pull request by jterry75**
Signed-off-by: Justin Terry (VM) <juterry@microsoft.com>

### CODE REVIEW

**Comment by mikebrow** [comment]
@Random-Liu account issue with travis

**Comment by jterry75** [comment]
@Random-Liu - ? This didnt fail any tests that I can understand. Can we re-run?

**Comment by mikebrow** [comment]
@yujuhong ping.. having a GCP service account issue..

**Comment by mikebrow** [comment]
@jterry75 my bad I didn't expand the log and misread it.. you need to run gofmt
```
I0619 15:42:00.653] !!! 'gofmt -s' needs to be run on the following files: 
120
I0619 15:42:00.654] ./pkg/server/instrumented_service.go
121
I0619 15:42:00.654] Makefile:71: recipe for target 'gofmt' failed
122
W0619 15:42:00.662] make: *** [gofmt] Error 1
123
W0619 15:42:00.662] Traceback (most recent call last):
124
W0619 15:42:00.662]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
125
W0619 15:42:00.662]     main(ARGS.env, ARGS.cmd + ARGS.args)
126
W0619 15:42:00.662]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
127
W0619 15:42:00.663]     check(*cmd)
128
W0619 15:42:00.663]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
129
W0619 15:42:00.663]     subprocess.check_call(cmd)
130
W0619 15:42:00.663]   File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
131
W0619 15:42:00.663]     raise CalledProcessError(retcode, cmd)
132
W0619 15:42:00.663] subprocess.CalledProcessError: Command '('./test/verify.sh',)' returned non-zero exit status 2
```

**Comment by jterry75** [comment]
@mikebrow - Thanks for looking. I don't understand where you saw that though. It looked like a permissions issue to me as well. Sorry for the confusion PR updated

**Comment by mikebrow** [comment]
> @mikebrow - Thanks for looking. I don't understand where you saw that though. It looked like a permissions issue to me as well. Sorry for the confusion PR updated

Yeah when I saw other builds passing.. I took another look.. the log scraper cut off the important part of the log (the first error). When that first error caused the build check to fail.. it then caused the pull to fail do to the pre-req of passing the first check... doh :)

**Comment by mikebrow** [comment]
I believe we moved make verify to kubeinfra because travis' would intermittently timeout on the lint test bucket. Maybe we should some of the make verify targets back into the travis bucket as travis is a little easier to manage.

**Comment by jterry75** [comment]
All green! Thanks @mikebrow

**Comment by jterry75** [comment]
@Random-Liu - PTAL I would love to get the context PR rebased on this so we can get those fixes in

**Comment by jterry75** [comment]
@Random-Liu ?

**Comment by jterry75** [comment]
@Random-Liu - ping?

**Comment by yujuhong** [comment]
@Random-Liu is out of office. 
/lgtm

**Comment by jterry75** [comment]
Thanks @yujuhong! I will rebase the other PR now.

**Pull request merged**
