### PR TITLE
[cherry-pick]support no_pivot option for runc

### PR DESCRIPTION
**Pull request by yanxuean**
Signed-off-by: yanxuean <yan.xuean@zte.com.cn>

### CODE REVIEW

**Comment by yanxuean** [comment]
Shame. 
I don't know how to cherry-pick a commit to another branch in github. I have never had this experience.
I have not searched for useful examples.
Is it correct?

**Comment by Random-Liu** [comment]
@yanxuean Yeah, just:
1) git checkout release/1.11
2) git cherrypick COMMIT_NUMBER
3) git push ...

I think you are doing correctly.

**Comment by yanxuean** [comment]
Thanks  @Random-Liu

**Pull request merged**
