### PR TITLE
Update to latest k8s 1.19.2 release

### PR DESCRIPTION
**Pull request by dims**
Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Comment by dims** [comment]
@mikebrow the failures do not seem to be flakes. can you please peek?

**Comment by mikebrow** [comment]
> @mikebrow the failures do not seem to be flakes. can you please peek?

kublet broken on 1.20 ...
master?

**Comment by mikebrow** [comment]
last full pass we didn't have a bucket named ResourceMetrics see: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/containerd_cri/1560/pull-cri-containerd-node-e2e/1298012253596946432

**Comment by mikebrow** [comment]
https://github.com/kubernetes/kubernetes/pull/93868

**Comment by mikebrow** [comment]
@MHBauer opened an issue:
https://github.com/kubernetes/kubernetes/issues/94493

**Comment by MHBauer** [comment]
5 failures in a row is very interesting!

**Comment by mikebrow** [comment]
so one pass out of 8 tries.. and when NodeProblemDetector passes there is different error reported and not caught by the test bucket: 
```Looking for address 'bootstrap-e2e-master-ip'
12489
ERROR: (gcloud.compute.addresses.describe) Could not fetch resource:
12490
 - The resource 'projects/cri-c8d-pr-node-e2e/regions/us-central1/addresses/bootstrap-e2e-master-ip' was not found
12491
```

**Comment by mikebrow** [comment]
Related: https://github.com/kubernetes/kubernetes/issues/94493

**Review by thaJeztah — APPROVED** [review]
LGTM

do we want to wait for the testing flakiness to be resolved, or are we comfortable merging? Had a look at the actual changes in the vendored files, and those changes look ok

**Comment by thaJeztah** [comment]
Just saw notification that v1.19.2 was released; do we want to stay in sync with patch releases? https://github.com/kubernetes/kubernetes/releases/tag/v1.19.2

**Comment by dims** [comment]
@thaJeztah yep will rev the PR

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by MHBauer** [comment]
Luck? Or something changed in .1 or .2?

**Comment by thaJeztah** [comment]
I think it's 🍀. At least (at a glance) didn't see anything that super stood-out to be different

@dims oh! missed that can you squash the commits, and update the PR title to `1.19.2` ?

**Comment by MHBauer** [comment]
eh, the commit messages are correct, which is what I care about.

**Comment by dims** [comment]
Fixed title and squashed commits. thanks @MHBauer @thaJeztah

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks 😊

**Review by mikebrow — APPROVED** [review]
LGTM

**Pull request merged**
