### PR TITLE
Do not cache image handler.

### PR DESCRIPTION
**Pull request by Random-Liu**
/cc @sofat1989 

Fixes https://github.com/containerd/containerd/issues/3401.

Signed-off-by: Lantao Liu <lantaol@google.com>

### CODE REVIEW

**Comment by mikebrow** [comment]
the change looks good... need to figure out the test failure though.

**Comment by Random-Liu** [comment]
There is some problem with this approach. Let me think about it a little bit.

**Comment by Random-Liu** [comment]
@mikebrow Fixed. The problem is that when `ImageStatus` returns an image, the image ID reference in containerd may not be ready yet.

I changed the PR to get an actual reference from the reference list, which ensures that the reference should exist in containerd.

**Comment by Random-Liu** [comment]
We should cherry-pick this to 1.2 to fix containerd/containerd#3401

**Pull request merged**
