### PR TITLE
[release/1.4] backport: ci: run test-integration target for all runtimes

### PR DESCRIPTION
**Pull request by samuelkarp**
cc @mikebrow @AkihiroSuda

### CODE REVIEW

**Comment by samuelkarp** [comment]
The Kubernetes e2e failures here do not look related to my change; the [same failures](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/containerd_cri/1600/pull-cri-containerd-node-e2e/1322333258645508096) occur on https://github.com/containerd/cri/pull/1600.

**Review by mikebrow — APPROVED** [review]
LGTM

**Comment by mikebrow** [comment]
the e2e node issue is a well known problem should be good to merge

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
