### PR TITLE
[WIP] Replacing nsenter with netns

### PR DESCRIPTION
**Pull request by abhi**
This commit has changes to replace the usage of nsenter with
netns. This can relax the requirement of requiring nsenter
installation.

Signed-off-by: Abhinandan Prativadi <abhi@docker.com>

### CODE REVIEW

**Comment by abhinandanpb** [comment]
Will update doc if we want to take this path

**Comment by Random-Liu** [comment]
Need to figure out how to solve https://github.com/vishvananda/netns/issues/17 and https://github.com/golang/go/issues/20676.

**Comment by Random-Liu** [comment]
The golang issue will be solved in golang 1.10. At that time, we could use `NetNS.Do` to run code inside the network namespace.

**Comment by abhinandanpb** [comment]
Woot Woot ! Thanks for the update @Random-Liu

**Pull request closed without merging**
