### PR TITLE
vendor: golang.org/x/crypto 1d94cc7ab1c630336ab82ccb9c9cda72a875c382

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/golang/crypto/compare/60c769a6c58655dab1b9adac0d58967dd517cfba...1d94cc7ab1c630336ab82ccb9c9cda72a875c382

I'm doing a around across repositories to update in preparation of a security release that was announced for tomorrow (so that we can update again with just the changes related to that fix);

https://groups.google.com/d/msgid/golang-announce/CA%2B2K_Kox3xkjj6gWkp%3DY6fmp7sO4T%2BbgudjjZZ%3Duwgp476pmEw%40mail.gmail.com

### CODE REVIEW

**Comment by mikebrow** [comment]
did you want to just add a commit to this PR tomorrow?

**Comment by thaJeztah** [comment]
I'm fine either way; my main reason was so that updating the security fix would be a small diff, and would (if needed) allow visual review of the diff (also to decide if it's important to backport to release branches).

**Pull request merged**
