### PR TITLE
update the slack information

### PR DESCRIPTION
**Pull request by mikebrow**
see... https://github.com/containerd/containerd/pull/2754
Signed-off-by: Mike Brown <brownwm@us.ibm.com>

### CODE REVIEW

**Comment by caniszczyk** [comment]
I'm hesitant to recommend the Docker Slack as it's corporate controlled and not neutral, can we just point people to a mailing list or other means for help?

**Comment by estesp** [comment]
As usual, momentum is a barrier to shifting gears mid-stream--the community has been in a set of channels on the community Slack team for a long time, with 660 people in our main channel at this point. To be clear, dockercommunity.slack.com is a free community Slack team separate from Docker's corporate slack; but yes, is operated/managed by dev rel team at Docker.

**Comment by estesp** [comment]
To be clear, we could put something else as a place for "help", but usually you want to point people to where discussion is actually happening and that is currently on the existing Slack channels that have been used for a few years now.

**Comment by mikebrow** [comment]
> I'm hesitant to recommend the Docker Slack as it's corporate controlled and not neutral, can we just point people to a mailing list or other means for help?

the mailing list is included below.. this is where we chat actively about containerd. This replaced the irc channels. There is a related sig-node channel, but really the conversations about containerd happen at the channels listed.

**Pull request merged**
