### PR TITLE
Update readme on how to configure cri plugin

### PR DESCRIPTION
**Pull request by qiujian16**
relates to https://github.com/containerd/cri/issues/718

### CODE REVIEW

**Comment by mikebrow** [comment]
@qiujian16 you need to sign the commit..

**Comment by Random-Liu** [comment]
@qiujian16 Please `git commit --amend -s` to sign your commit.

**Comment by mikebrow** [comment]
Set user.* entries to global and/or local:
$ git config --local user.name "Full name here"
$ git config --local user.email "email address here"
Or:
$ git config --global user.name "Full name here"
$ git config --global user.email "email address here"

Then sign the existing commit: 
$ git commit -s --amend

Then force push... to update existing commit:
$ git push -f origin qj_update_reademe

**Comment by Random-Liu** [comment]
@qiujian16 Thanks for your fix! :)

**Pull request merged**
