### PR TITLE
adds git hub actions for linux CI

### PR DESCRIPTION
**Pull request by mikebrow**
address #1444

Will delete our .travis.yml tests after we merge this

Signed-off-by: Mike Brown <brownwm@us.ibm.com>

### CODE REVIEW

**Comment by mikebrow** [comment]
@dims FYI...

**Comment by dims** [comment]
w00t! @mikebrow 

the "Build and Test" should probably be a separate job from the verify in a subsequent PR

LGTM

**Comment by estesp** [comment]
Looks great--nice work @mikebrow ! LGTM

**Comment by mikebrow** [comment]
> w00t! @mikebrow
> 
> the "Build and Test" should probably be a separate job from the verify in a subsequent PR
> 
> LGTM

Don't disagree.. was just going with how we did it in travis. :-)

**Pull request merged**
