### PR TITLE
Replace docker/distribution/reference with containerd/reference/docker

### PR DESCRIPTION
**Pull request by zhsj**
Since https://github.com/containerd/containerd/pull/3728
The docker/distribution/reference package is copied into containerd core

### CODE REVIEW

**Comment by zhsj** [comment]
This updates https://github.com/containerd/cri/pull/1377, so no need a new docker/distribution release.

cc @chenrui333

**Comment by mikebrow** [comment]
@zhsj pls rebase.. pull-cri-containerd-windows-cri test has been moved to git hub actions.

**Comment by zhsj** [comment]
> @zhsj pls rebase.. pull-cri-containerd-windows-cri test has been moved to git hub actions.

Done, and commit is also split.

**Pull request merged**
