### PR TITLE
[WIP] adds option for setting oci hooks

### PR DESCRIPTION
**Pull request by mikebrow**
To address issue containerd/containerd#6645 I've started a prototype.

User must generate a json file for the hooks struct: https://github.com/opencontainers/runtime-spec/blob/master/specs-go/config.go#L114-L130

Hooks explained here: https://github.com/opencontainers/runtime-spec/blob/master/config.md#prestart

Signed-off-by: Mike Brown <brownwm@us.ibm.com>

### CODE REVIEW

**Comment by Random-Liu** [comment]
@mikebrow Why do we need this feature at cri-containerd level? This should be driven by CRI, right?

**Comment by mikebrow** [comment]
> @mikebrow Why do we need this feature at cri-containerd level? This should be driven by CRI, right?

Yes, it should be driven by CRI. I put it here for prototyping only.

**Comment by lizrice** [comment]
We'd like to be able to configure prestart hooks, and this (or something like this) would give us just what we need. Our case is to hook in a security tool on prestart; our users would have the same hook configured on every node (or at least on every node where they want the tool to run), and the same hook would run for all containers. 

It would be nice to be able to add the hook without a restart, but not essential.

**Comment by egernst** [comment]
@mikebrow @lizrice @Random-Liu  -- I am hopeful that there's some traction/forward progress here.  Any insights on how to drive this forward in containerd?

**Comment by krsna1729** [comment]
Need this functionality to do device provisioning at prestart and poststop stage of container lifecycle. Only cri-o seems to be supporting. It would be great if its part of CRI, or atleast containerd supports.

**Comment by alban** [comment]
I mentioned this issue for discussion in a previous [OCI meeting](https://groups.google.com/a/opencontainers.org/forum/#!forum/dev) ([notes](https://hackmd.io/El8Dd2xrTlCaCG59ns5cwg?view#July-24-2019), [slides](https://docs.google.com/presentation/d/1i8csKAf15j3ZDeHxuUlHBDvHiBI44_UxATdaaAy-pjE/edit)) and I would like to mention it at the next [Kubernetes SIG Node](https://github.com/kubernetes/community/tree/master/sig-node) meeting ([notes](https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit#heading=h.n6dc6gp6gik8)).

**Comment by mikebrow** [comment]
moving PR to PR containerd/cri#1248 as this branch has been deleted...

**Pull request closed without merging**
