### PR TITLE
[release/1.4] append envs from image config to empty slice to avoid env lost

### PR DESCRIPTION
**Pull request by zhsj**
Backport https://github.com/containerd/containerd/pull/5024 and https://github.com/containerd/containerd/pull/5054

### CODE REVIEW

**Review by kevpar — APPROVED** [review]
LGTM

**Review by Zyqsempai — APPROVED** [review]
LGTM

**Comment by fuweid** [comment]
> pull-cri-containerd-node-e2e Pending — Job triggered

The CI doesn't update the status.

**Comment by fuweid** [comment]
> zone=us-central1-f --ssh-user=prow --ssh-key=/workspace/.ssh/google_compute_engine --ginkgo-flags=--nodes=8 --focus="\[NodeConformance\]|\[NodeFeature:.+\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]" --test_args=--container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock --container-runtime-process-name=/home/containerd/usr/local/bin/containerd --container-runtime-pid-file= --kubelet-flags="--cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd\"]}" --test-timeout=1h5m0s --image-config-file=/home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/containerd/cri-master/image-config-pr.yaml -node-env=PULL_REFS=release/1.4:b4b894c871860664fe5c0509df68da0dbae9f095,1628:e4fcda3215cc607cc1f10657f76cbf85313fd64c (interrupted): exit status 1

Looks like it is CI issue. Not related to the change.

**Comment by mikebrow** [comment]
@dims did the path change .. `cri-c8d-pr-node-e2e` for both containerd/containerd and containerd/cri infra? 

```
Looking for address 'bootstrap-e2e-master-ip'
ERROR: (gcloud.compute.addresses.describe) Could not fetch resource:
 - The resource 'projects/cri-c8d-pr-node-e2e/regions/us-central1/addresses/bootstrap-e2e-master-ip' was not found
```

**Review by mikebrow — APPROVED** [review]
LGTM

**Pull request merged**
