### PR TITLE
Fix doc for runtime specific options

### PR DESCRIPTION
**Pull request by hckuo**
Signed-off-by: Hsuan-Chi Kuo <hckuo2@illinois.edu>

### CODE REVIEW

**Comment by mikebrow** [comment]
have to sign both commits pls..

**Comment by AkihiroSuda** [comment]
Why? The previous form should have been functional?

**Comment by mikebrow** [comment]
pulled it down to check why it's failing..
commit header is missing blank line between commit description and signature
```
include missed NoPivotRoot
Signed-off-by: Hsuan-Chi Kuo <hckuo2@illinois.edu>
```

**Comment by hckuo** [comment]
Squashed two commits

**Comment by khs1994** [comment]
@AkihiroSuda  this change is mistake?

set `binary_name` no effect

set `BinaryName`  have effect

**Comment by khs1994** [comment]
ping @mikebrow

**Comment by AkihiroSuda** [comment]
Yes, seems mistake. Opened a PR to revert this: https://github.com/containerd/cri/pull/1584

**Pull request merged**
