### PR TITLE
missed the release version for HEAD in table-1

### PR DESCRIPTION
**Pull request by mikebrow**
minor update regarding HEAD support
Signed-off-by: Mike Brown <brownwm@us.ibm.com>

### CODE REVIEW

**Comment by Random-Liu** [comment]
It is reflected in the second table, right?

**Comment by mikebrow** [comment]
> It is reflected in the second table, right?

Yes kube n-1 version number is reflected in the second table, not the first. 

Alternatively we could just remove the HEAD support row...

**Comment by Random-Liu** [comment]
> Alternatively we could just remove the HEAD support rows...

SG. :)

**Pull request merged**
