### PR TITLE
fix private docker registry configuration

### PR DESCRIPTION
**Pull request by guoruijing**
Signed-off-by: Guo Ruijing <ruijing.guo@intel.com>

### CODE REVIEW

**Comment by mikebrow** [comment]
@Random-Liu we're getting hit by the log problem mentioned in the sig-node meeting.

**Comment by Random-Liu** [comment]
@mikebrow Looking into this right now.

**Comment by Random-Liu** [comment]
@guoruijing I don't quite understand your change. The original document seems correct to me.

Can you add some explanation?

**Comment by guoruijing** [comment]
example with issue:
1.  config in /etc/containerd/config.toml
    [plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."registry"]
          endpoint = ["http://registry:5000"]
2. restart containerd
3. pull images:
vagrant@worker1:~$ sudo crictl pull registry:5000/multus-cni
FATA[0000] pulling image failed: rpc error: code = Unknown desc = failed to resolve image "registry:5000/multus-cni:latest": no available registry endpoint: failed to do request: Head https://registry:5000/v2/multus-cni/manifests/latest: http: server gave HTTP response to HTTPS client

**Comment by guoruijing** [comment]
I don't know how to build cri now and I remember the issue in pkg/server/image_pull.go

func (c *criService) getResolver(ctx context.Context, ref string, cred func(string) (string, string, error)) (remotes.Resolver, imagespec.Descriptor, error) {
        refspec, err := reference.Parse(ref)
        if err != nil {
                return nil, imagespec.Descriptor{}, errors.Wrap(err, "parse image reference")
        }
        // Try mirrors in order first, and then try default host name.
        for _, e := range c.config.Registry.Mirrors[refspec.Hostname()].Endpoints {

refspec.Hostname also include hostname & port. if configuration doesn't include port, then it mismatch and cannot find docker registry.

**Comment by Random-Liu** [comment]
@guoruijing I feel like with your config, you should pull `registry/multus-cni` instead. And containerd will know it should access `http://registry:5000` based on your registry mirror config.

**Comment by Random-Liu** [comment]
@guoruijing Do you still need anything?

**Comment by Random-Liu** [comment]
I'll close this for now. Feel free to reopen if you still want it. :)

**Pull request closed without merging**
