### PR TITLE
[release/1.3]  Sync vendors with containerd 1.3.2

### PR DESCRIPTION
**Pull request by dims**
Look through the `containerd dependencies` in vendor.conf, for each
dependency / SHA, check if the SHA is newer in containerd's vendor.conf
in 1.3.2 tag. Update if necessary.

Drop unused packages. Add versions for missing packages.

cherry pick https://github.com/containerd/cri/commit/2ce0bb0926b54bf2aeec6d9914d2336202a5adb9 as well to drop broken test

### CODE REVIEW

**Comment by dims** [comment]
whoops fixing 2nd commit!

**Comment by dims** [comment]
@mikebrow is there a way to re-trigger the travis CI build?

**Comment by dims** [comment]
@thaJeztah @mikebrow looks like the `TestUnknownStateAfterContainerdRestart` was removed from master in https://github.com/containerd/cri/commit/2ce0bb0926b54bf2aeec6d9914d2336202a5adb9 should it be removed in release/1.3 too?

**Comment by mikebrow** [comment]
> @thaJeztah @mikebrow looks like the `TestUnknownStateAfterContainerdRestart` was removed from master in [2ce0bb0](https://github.com/containerd/cri/commit/2ce0bb0926b54bf2aeec6d9914d2336202a5adb9) should it be removed in release/1.3 too?

Yes, it should.

**Comment by thaJeztah** [comment]
Looks like that was this PR: https://github.com/containerd/cri/pull/1309, which related to https://github.com/containerd/containerd/pull/3711, and was back ported to the containerd 1.3 branch in https://github.com/containerd/containerd/pull/3753, so yes looks like it needs to be backported

**Comment by thaJeztah** [comment]
oh, LOL @mikebrow beated me to it (high five! ✋)

**Comment by dims** [comment]
@thaJeztah @mikebrow i've added another commit with the backport for dropping the broken test. thanks!

**Pull request merged**
