### PR TITLE
[release/1.0] Update containerd to 878924b9b5b2d5fc22a3bdbe93ac736f31618f44.

### PR DESCRIPTION
**Pull request by Random-Liu**
Signed-off-by: Lantao Liu <lantaol@google.com>

### CODE REVIEW

**Comment by mikebrow** [comment]
```
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/expansion.go:156
Expected error:
    <*errors.errorString | 0xc000b207b0>: {
        s: "expected \"0\" in container output: Expected\n    <string>: 1\n    \nto contain substring\n    <string>: 0",
    }
    expected "0" in container output: Expected
        <string>: 1
        
    to contain substring
        <string>: 0
not to have occurred
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2325

```

sigh... :)

**Comment by Random-Liu** [comment]
This looks bad:
```
Feb 15 17:14:06.272: INFO: At 2019-02-15 17:14:05 +0000 UTC - event for pod-init-17350f24-3145-11e9-8a08-42010a800019: {kubelet tmp-node-e2e-0b1d3070-cos-stable-60-9592-84-0} Failed: Error: failed to start containerd task "init2": OCI runtime start failed: container process is already dead: unknown
```

**Pull request merged**
