### PR TITLE
[release/1.3] vendor: containerd v1.3.7 and dependencies

### PR DESCRIPTION
**Pull request by thaJeztah**
First two commits are reformatting the vendor.conf to use the same format as containerd upstream (for easier comparison)

### CODE REVIEW

**Comment by thaJeztah** [comment]
Arf; so there were some new dependencies; fixing

```
vendor/github.com/containerd/containerd/pkg/process/io.go:40:2: cannot find package "github.com/hashicorp/go-multierror" in any of:
	/home/prow/go/src/github.com/containerd/cri/vendor/github.com/hashicorp/go-multierror (vendor tree)
	/usr/local/go/src/github.com/hashicorp/go-multierror (from $GOROOT)
	/home/prow/go/src/github.com/hashicorp/go-multierror (from $GOPATH)
```

**Comment by thaJeztah** [comment]
Ah! I see golang-ci-lint installation is failing;

```
I1118 23:23:20.610] go get -d github.com/golangci/golangci-lint/cmd/golangci-lint
W1118 23:23:59.421] package 4d63.com/gochecknoglobals/checknoglobals: unrecognized import path "4d63.com/gochecknoglobals/checknoglobals": reading https://4d63.com/gochecknoglobals/checknoglobals?go-get=1: 404 Not Found
W1118 23:24:39.445] make: *** [Makefile:173: .install.golangci-lint] Error 1
W1118 23:24:39.447] Traceback (most recent call last):
W1118 23:24:39.447]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W1118 23:24:39.447]     main(ARGS.env, ARGS.cmd + ARGS.args)
W1118 23:24:39.448]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W1118 23:24:39.448]     check(*cmd)
W1118 23:24:39.448]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W1118 23:24:39.448]     subprocess.check_call(cmd)
W1118 23:24:39.448]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W1118 23:24:39.448]     raise CalledProcessError(retcode, cmd)
W1118 23:24:39.449] subprocess.CalledProcessError: Command '('./test/verify.sh',)' returned non-zero exit status 2
```

Same issue as I ran into in https://github.com/moby/moby/pull/41560

**Comment by thaJeztah** [comment]
Opened https://github.com/containerd/cri/pull/1611 to fix CI

**Comment by thaJeztah** [comment]
rebased, as https://github.com/containerd/cri/pull/1611 was merged

**Review by AkihiroSuda — APPROVED** [review]

**Review by mikebrow — APPROVED** [review]
LGTM

**Pull request merged**
