### PR TITLE
Update containerd to 4543e32a8b29e691e523ddc142f0c9068917df54

### PR DESCRIPTION
**Pull request by thaJeztah**
This removes the last use of `util.NormalizeImageRef`

Let me know if you want to have this utility removed, or to keep it for backward compatibility (not sure if this repository is vendored elsewhere, and the utility used by other projects)

### CODE REVIEW

**Comment by mikebrow** [comment]
Yes, let's leave it for now flagged deprecated and simply forwarding on, as you did in the prior PR.

Thanks @thaJeztah!

**Comment by thaJeztah** [comment]
👍 I opened a PR in containerd for the 1.2 release branch, and once that's merged, will do another round to get it into the cri 1.x release branch as well (argh those circular dependencies, hahaha)

**Comment by Random-Liu** [comment]
Somethign wrong in the test-infra, fixing it now. :)

**Comment by thaJeztah** [comment]
🎉 it's green now (thanks for helping with CI!)

**Comment by Random-Liu** [comment]
Test passes, but there is still something wrong with how the test report shows up.

Anyway, I'll merge this change first.

**Pull request merged**
