### PR TITLE
[release/1.4] Fix cleanup context of teardownPodNetwork

### PR DESCRIPTION
**Pull request by adisky**
Cherry pick from [commit](https://github.com/containerd/containerd/commit/728743eb2858764df05fbb012cb03eb7c6cb0423) 

Co-authored-by: Quan Tian <qtian@vmware.com>

Signed-off-by: Aditi Sharma <adi.sky17@gmail.com>

### CODE REVIEW

**Comment by adisky** [comment]
cc @dims

**Review by dims — APPROVED** [review]
LGTM

**Review by Zyqsempai — APPROVED** [review]
LG

**Review by AkihiroSuda — APPROVED** [review]

**Review by fuweid — APPROVED** [review]

**Comment by xh4n3** [comment]
@fuweid Hi~ do we have a plan for containerd 1.4.7 include this fix?

**Comment by fuweid** [comment]
@xh4n3 Sure, we do have plan, but we need to update vendor first. :)

**Pull request merged**
