### PR TITLE
test: Fix compile error with go1.10.2

### PR DESCRIPTION
**Pull request by amshinde**
Replace Skip with Skipf in the intergration test.

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by Random-Liu** [comment]
/lgtm

The failure is caused by golang version issue. I'll update the test-infra.

**Comment by Random-Liu** [comment]
Let's wait for https://github.com/kubernetes/test-infra/pull/9736.

**Comment by amshinde** [comment]
@Random-Liu I see the pull-cri-containerd-verify tests failing. Do these need to be rerun or is this a valid failure?

**Pull request merged**
