### PR TITLE
removes authconfig from info log

### PR DESCRIPTION
**Pull request by mikebrow**
address #960

Signed-off-by: Mike Brown <brownwm@us.ibm.com>

### CODE REVIEW

**Comment by Random-Liu** [comment]
@yujuhong Also mentioned this issue to me before.

**Comment by Random-Liu** [comment]
@mikebrow Let's cherrypick this into all supported branches.

**Comment by mikebrow** [comment]
> @mikebrow Let's cherrypick this into all supported branches.

SGTM .. and done :-)

**Pull request merged**
