### PR TITLE
update cni config version

### PR DESCRIPTION
**Pull request by mikebrow**
See: https://github.com/containerd/containerd/pull/4308/files#diff-bc3ee81027bc2e27f4df56465b4290e1R37

https://github.com/containerd/containerd/pull/4308

Signed-off-by: Mike Brown <brownwm@us.ibm.com>

### CODE REVIEW

**Comment by mikebrow** [comment]
@aojea FYI

**Review by thaJeztah — APPROVED** [review]
SGTM, thanks!

**Comment by aojea** [comment]
nice, ecosystem moving up :+1:

**Review by fuweid — APPROVED** [review]
LGTM

**Pull request merged**
