### PR TITLE
Fixs return error message

### PR DESCRIPTION
**Pull request by JoeWrightss**
Fixs typo: "intialized" to "initialized" in [sandbox_stop.go](https://github.com/containerd/cri/compare/master...JoeWrightss:patch-3?expand=1#diff-55c3fa2c53574320c3a17ebe3d4ad5d3) and [errors.go](https://github.com/containerd/cri/compare/master...JoeWrightss:patch-3?expand=1#diff-5dc4ac8ca72c915f458ed3bf572c7d3f).

### CODE REVIEW

**Comment by Random-Liu** [comment]
@JoeWrightss Please don't update vendor code directly. Please fix it in go-cni, and then vendor it.

**Comment by mikebrow** [comment]
or fix in go-cni and we'll vendor it at some point in the future...

**Pull request closed without merging**
