### PR TITLE
always update image in cri image store

### PR DESCRIPTION
**Pull request by sofat1989**
Fix: https://github.com/containerd/containerd/issues/3401

### CODE REVIEW

**Comment by Random-Liu** [comment]
Hm, I feel like the problem is that we should not cache `containerd.Image` in our image store, because it can never be up to date given that fields like `Target`, `Labels` and `UpdatedAt` can all change.

**Comment by mikebrow** [comment]
> Hm, I feel like the problem is that we should not cache `containerd.Image` in our image store, because it is hard to keep it up to date given that fields like `Target`, `Labels` and `UpdatedAt` can all change.

I don't disagree at this point in time.  It made more sense back when we were a remote daemon than it does now that we are a local plugin.

**Comment by Random-Liu** [comment]
See https://github.com/containerd/cri/pull/1202

**Comment by Random-Liu** [comment]
This should have been fxied by #1202.

Close for now.

Feel free to reopen if that doesn't solve your problem. :) @sofat1989

**Pull request closed without merging**
