### PR TITLE
CreateContainerRequest should use PodSandboxConfig based on ID

### PR DESCRIPTION
**Pull request by jterry75**
Signed-off-by: Justin Terry (VM) <juterry@microsoft.com>

### CODE REVIEW

**Comment by jterry75** [comment]
@crosbymichael @Random-Liu - FYI. It turns out this causes an AV and crashes CRI if you send `nil` here. But the spec allows for `nil` and is only sent by convention.

**Comment by jterry75** [comment]
No the goal is not to *harden* the API. As you point out a `nil` for `Config` would also AV CRI. However, we do not allow an empty `PodSandboxId` as we will fail the sandbox store check. Personally it doesnt make sense to me why you would be allowed to pass a `PodSandboxConfig` here given that it is **immutable in the lifetime of the pod** but that seems to be the API. Why would we ever take the passed in `SandboxConfig` over the one resolved via `PodSandboxId`?

**Comment by jterry75** [comment]
Interestingly: [cri-o](https://github.com/kubernetes-sigs/cri-o/blob/71f84607110e1d9cba2f7012ba338528304c7fc7/server/container_create.go#L439) seems to follow this logic:
- `PodSandboxId` Required.
- `Config` Required.
- `SandboxConfig` Optional - Will not AV if not passed. BUT: [uses](https://github.com/kubernetes-sigs/cri-o/blob/8bbac5e061150c64f7434b742a907a0168e545d6/server/container_create_linux.go#L255) `sandboxConfig.GetLinux().GetSecurityContext().GetPrivileged()` and `sandboxConfig.GetLogDirectory()`.

So technically it wouldn't AV in the case we are but it would allow me to change the `SandboxConfig` options and have them used.

**Comment by Random-Liu** [comment]
In what case the sandbox config will be nil? I don’t think that is allowed.

I think the reason we pass sandboxconfig again here is to avoid the
necessity to checkpoint it in the runtime. We do checkpoint it in
containerd, but dockershim doesn’t.

I think it should never be nil.

**Comment by jterry75** [comment]
@Random-Liu - I don't follow. What do you mean *we need to checkpoint*. All this does is give CRI the sandbox config as it was originally passed via `RunPodSandbox`. If you are worried about a regression here I can make it only use the in-memory version if it is not `nil`.

**Comment by Random-Liu** [comment]
I mean RunPodSandbox and CreateContainer are different request. To use the
sandbox config passed in RunPodSandbox in CreateContainer, we need to
checkpoint the sandbox config we get in RunPodSandbox. That is what sandbox
store does.

However, CRI doesn’t expect the runtime to do that, and dockershim doesn’t
do that, either. That is why we pass sandbox config again to
CreateContainer.

So in short, SandboxConfig passed to CreateContainer should not be nil, we
should be able to rely on it.

**Comment by jterry75** [comment]
Ah. Ok no issues then. And we don't care about protecting against the AV in favor of a better error?

**Comment by mikebrow** [comment]
> Ok no issues then. And we don't care about protecting against the AV in favor of a better error?

Thus my points about hardening and testing. One would need to modify the CRI docs to make the desired behavior explicit, develop the tests to ensure the desired behavior is correct, and add prs to the popular container runtimes as well. Otherwise we go with tyranny of the first implementor, docker shim :-)

**Comment by jterry75** [comment]
Sounds good then closing.

**Pull request closed without merging**
