### PR TITLE
[release/1.4] update Go 1.15.5 (to match containerd)

### PR DESCRIPTION
**Pull request by thaJeztah**
Follow-up to https://github.com/containerd/cri/pull/1607

Changes: https://golang.org/doc/devel/release.html#go1.15

### CODE REVIEW

**Comment by thaJeztah** [comment]
rebased 👍 🤞

**Review by estesp — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Seeing failures; not sure if related (perhaps need to check if changes went into containerd 1.4 to fix Go 1.15, and if we need to update containerd vendoring as well)

**Comment by AkihiroSuda** [comment]
>   failed to create TempDir "": pattern contains path separator

critest needs to have https://github.com/kubernetes-sigs/cri-tools/pull/646 for Go 1.15

**Comment by mikebrow** [comment]
> > failed to create TempDir "": pattern contains path separator
> 
> critest needs to have [kubernetes-sigs/cri-tools#646](https://github.com/kubernetes-sigs/cri-tools/pull/646) for Go 1.15

https://github.com/containerd/cri/blob/release/1.4/hack/utils.sh#L21 for ci here in containerd/cri

**Comment by thaJeztah** [comment]
Updated critools to the same commit as containerd "master" currently uses (0f5f734a7e1da0979915c6e7d5b6641bd9dc2627), which is some commits ahead of the commit @AkihiroSuda referred to above (https://github.com/kubernetes-sigs/cri-tools/compare/2bf7674922a424337d7580a08166d666c6802818...0f5f734a7e1da0979915c6e7d5b6641bd9dc2627)

**Review by mikebrow — APPROVED** [review]
LGTM

**Comment by mikebrow** [comment]
The e2e node issue is a well known problem... should be good to go.

**Review by dmcgowan — APPROVED** [review]
LGTM

**Pull request merged**
