### PR TITLE
[release/1.4 backport] Update to latest kubernetes v1.19.2

### PR DESCRIPTION
**Pull request by thaJeztah**
backport of https://github.com/containerd/cri/pull/1562 for the 1.4 branch
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
(cherry picked from commit da4a8aea15e523c7b16da0ba5fde9e39a46dbd35)
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

### CODE REVIEW

**Review by Zyqsempai — APPROVED** [review]
LGTM

**Review by mikebrow — APPROVED** [review]
LGTM

**Comment by mikebrow** [comment]
node problem detector seems to  be more touchy in the afternoon

**Pull request merged**
