### PR TITLE
update for containerd vendor changes

### PR DESCRIPTION
**Pull request by mikebrow**
A number of vendor changes need to be done to start synching up with containerd/vendor.conf changes that went in last month up to commit 1fb1d93212af763bd481b476293040b1566ae00b  also addresses #1369 

Signed-off-by: Mike Brown <brownwm@us.ibm.com>

### CODE REVIEW

**Comment by jterry75** [comment]
@mikebrow - Code looks fine but CI is permissions issue

**Comment by mikebrow** [comment]
@yujuhong @Random-Liu any idea why gcloud.compute.ssh can't SSH into the windows CI instance?

**Comment by jterry75** [comment]
Wahoo!

**Pull request merged**
