### PR TITLE
Do not remove image when it is being used by a container

### PR DESCRIPTION
**Pull request by Random-Liu**
For https://github.com/containerd/cri/issues/990.

This PR:
1) Added a check in image_remove.go to make sure image can only be removed when it is not used by a container;
2) Added a `leases` field in `Image` to avoid the race condition between the check and container creation.

### CODE REVIEW

**Comment by mikebrow** [comment]
@Random-Liu says no merge conflicts but maybe we should rebase and retest after the recent changes?

**Comment by Random-Liu** [comment]
@mikebrow Rebased.

Note that this PR also changes the test containerd binary to be `containerd-test`, so that we can easily restart containerd in the test without breaking Docker 18.09+ on the node.

**Comment by Random-Liu** [comment]
Hm, I'm really not sure whether we need this...

Let's wait for our customers' feedback. If removing image when containers exist cause issue in the future, we can always get back to this...

**Comment by dmcgowan** [comment]
The master branch on this repository has been merged into [containerd/containerd](https://github.com/containerd/containerd). If we still need this, we can add it back there.

**Pull request closed without merging**
