### PR TITLE
[WCOW] Add container compute stats support.

### PR DESCRIPTION
**Pull request by Random-Liu**
Fixes https://github.com/containerd/cri/issues/1275.

Ref https://github.com/kubernetes/kubernetes/issues/82522

/cc @jterry75 @yliaog 

Signed-off-by: Lantao Liu <lantaol@google.com>

### CODE REVIEW

**Comment by Random-Liu** [comment]
Here is an example output:
<details>
```
crictl stats -o json
{
  "stats": [
    {
      "attributes": {
        "id": "0e70a82a114f3b38610da0a302d09a8b6aefac9f58fe7aad7eba856b5003841a",
        "metadata": {
          "name": "nanoserver-6",
          "attempt": 0
        },
        "labels": {
        },
        "annotations": {
        }
      },
      "cpu": {
        "timestamp": "1572041798995566100",
        "usageCoreNanoSeconds": {
          "value": "2656250000"
        }
      },
      "memory": {
        "timestamp": "1572041798995566100",
        "workingSetBytes": {
          "value": "25317376"
        }
      },
      "writableLayer": {
        "timestamp": "1572041797927167200",
        "fsId": {
          "mountpoint": "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows"
        },
        "usedBytes": {
          "value": "0"
        },
        "inodesUsed": {
          "value": "0"
        }
      }
    },
    {
      "attributes": {
        "id": "10a88cd65c75d386e579220f70baa5b0075f515d35e065a3aa86eb9055ea0a16",
        "metadata": {
          "name": "nanoserver-3",
          "attempt": 0
        },
        "labels": {
        },
        "annotations": {
        }
      },
      "cpu": {
        "timestamp": "1572041799023814100",
        "usageCoreNanoSeconds": {
          "value": "3359375000"
        }
      },
      "memory": {
        "timestamp": "1572041799023814100",
        "workingSetBytes": {
          "value": "25247744"
        }
      },
      "writableLayer": {
        "timestamp": "1572041797927167200",
        "fsId": {
          "mountpoint": "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows"
        },
        "usedBytes": {
          "value": "0"
        },
        "inodesUsed": {
          "value": "0"
        }
      }
    },
    {
      "attributes": {
        "id": "4735691009c5f9bdacf409d3e7b6b81af24dc45d270cb8c781c9ed946f4cfe74",
        "metadata": {
          "name": "nanoserver-7",
          "attempt": 0
        },
        "labels": {
        },
        "annotations": {
        }
      },
      "cpu": {
        "timestamp": "1572041798999441500",
        "usageCoreNanoSeconds": {
          "value": "2578125000"
        }
      },
      "memory": {
        "timestamp": "1572041798999441500",
        "workingSetBytes": {
          "value": "25563136"
        }
      },
      "writableLayer": {
        "timestamp": "1572041797927167200",
        "fsId": {
          "mountpoint": "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows"
        },
        "usedBytes": {
          "value": "0"
        },
        "inodesUsed": {
          "value": "0"
        }
      }
    },
    {
      "attributes": {
        "id": "58073101c471cbc35c926fd0a3ef5a0caddd94646de7fca87d56d2572d591aac",
        "metadata": {
          "name": "nanoserver-5",
          "attempt": 0
        },
        "labels": {
        },
        "annotations": {
        }
      },
      "cpu": {
        "timestamp": "1572041799018938800",
        "usageCoreNanoSeconds": {
          "value": "2656250000"
        }
      },
      "memory": {
        "timestamp": "1572041799018938800",
        "workingSetBytes": {
          "value": "24993792"
        }
      },
      "writableLayer": {
        "timestamp": "1572041797927167200",
        "fsId": {
          "mountpoint": "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows"
        },
        "usedBytes": {
          "value": "0"
        },
        "inodesUsed": {
          "value": "0"
        }
      }
    },
    {
      "attributes": {
        "id": "5e7d99e0147e76d3c9c9f75206c06f6e59f9924c2a271158a6ff9197010f56bb",
        "metadata": {
          "name": "nanoserver-9",
          "attempt": 0
        },
        "labels": {
        },
        "annotations": {
        }
      },
      "cpu": {
        "timestamp": "1572041799006230900",
        "usageCoreNanoSeconds": {
          "value": "2609375000"
        }
      },
      "memory": {
        "timestamp": "1572041799006230900",
        "workingSetBytes": {
          "value": "24850432"
        }
      },
      "writableLayer": {
        "timestamp": "1572041797927167200",
        "fsId": {
          "mountpoint": "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows"
        },
        "usedBytes": {
          "value": "0"
        },
        "inodesUsed": {
          "value": "0"
        }
      }
    },
    {
      "attributes": {
        "id": "85d5e2d90194be703a91c9c1609eca814a64556aa7eef0c5a01559912661171f",
        "metadata": {
          "name": "nanoserver-1",
          "attempt": 0
        },
        "labels": {
        },
        "annotations": {
        }
      },
      "cpu": {
        "timestamp": "1572041799012653600",
        "usageCoreNanoSeconds": {
          "value": "3234375000"
        }
      },
      "memory": {
        "timestamp": "1572041799012653600",
        "workingSetBytes": {
          "value": "25051136"
        }
      },
      "writableLayer": {
        "timestamp": "1572041797927167200",
        "fsId": {
          "mountpoint": "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows"
        },
        "usedBytes": {
          "value": "0"
        },
        "inodesUsed": {
          "value": "0"
        }
      }
    },
    {
      "attributes": {
        "id": "af8a70bd05b8b37161c4f8bc523b2999e756993d0ea642c23bb94ed364f4a139",
        "metadata": {
          "name": "nanoserver-4",
          "attempt": 0
        },
        "labels": {
        },
        "annotations": {
        }
      },
      "cpu": {
        "timestamp": "1572041799016097000",
        "usageCoreNanoSeconds": {
          "value": "3125000000"
        }
      },
      "memory": {
        "timestamp": "1572041799016097000",
        "workingSetBytes": {
          "value": "24752128"
        }
      },
      "writableLayer": {
        "timestamp": "1572041797927167200",
        "fsId": {
          "mountpoint": "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows"
        },
        "usedBytes": {
          "value": "0"
        },
        "inodesUsed": {
          "value": "0"
        }
      }
    },
    {
      "attributes": {
        "id": "dfe41d01b7728fcfd25302725abd550960277b8875333fb86eb0b6b5d318a4ec",
        "metadata": {
          "name": "nanoserver-8",
          "attempt": 0
        },
        "labels": {
        },
        "annotations": {
        }
      },
      "cpu": {
        "timestamp": "1572041799003325200",
        "usageCoreNanoSeconds": {
          "value": "2562500000"
        }
      },
      "memory": {
        "timestamp": "1572041799003325200",
        "workingSetBytes": {
          "value": "24752128"
        }
      },
      "writableLayer": {
        "timestamp": "1572041797927167200",
        "fsId": {
          "mountpoint": "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows"
        },
        "usedBytes": {
          "value": "0"
        },
        "inodesUsed": {
          "value": "0"
        }
      }
    },
    {
      "attributes": {
        "id": "f49f5fe91d7b11e856d90c21d6e28aec21add8d64bca247b2ae5d2c1a684ae1f",
        "metadata": {
          "name": "nanoserver-2",
          "attempt": 0
        },
        "labels": {
        },
        "annotations": {
        }
      },
      "cpu": {
        "timestamp": "1572041799020885200",
        "usageCoreNanoSeconds": {
          "value": "3359375000"
        }
      },
      "memory": {
        "timestamp": "1572041799020885200",
        "workingSetBytes": {
          "value": "24924160"
        }
      },
      "writableLayer": {
        "timestamp": "1572041797927167200",
        "fsId": {
          "mountpoint": "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows"
        },
        "usedBytes": {
          "value": "0"
        },
        "inodesUsed": {
          "value": "0"
        }
      }
    },
    {
      "attributes": {
        "id": "fca0e3d79ea54916de7fc0e44b2f4e8c3d7b121ed3c4f3ecf5cebd848d69e633",
        "metadata": {
          "name": "nanoserver",
          "attempt": 0
        },
        "labels": {
        },
        "annotations": {
        }
      },
      "cpu": {
        "timestamp": "1572041799009196500",
        "usageCoreNanoSeconds": {
          "value": "3734375000"
        }
      },
      "memory": {
        "timestamp": "1572041799009196500",
        "workingSetBytes": {
          "value": "24748032"
        }
      },
      "writableLayer": {
        "timestamp": "1572041797927167200",
        "fsId": {
          "mountpoint": "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows"
        },
        "usedBytes": {
          "value": "0"
        },
        "inodesUsed": {
          "value": "0"
        }
      }
    }
  ]
}
```
</details>

**Comment by jterry75** [comment]
@katiewasnothere - Can you give a quick double check here

**Comment by jterry75** [comment]
@PatrickLang - FYI

**Comment by jterry75** [comment]
Ref: #1257

**Comment by Random-Liu** [comment]
Apply LGTM based on LGTMs above.

**Pull request merged**
