### PR TITLE
Update kubernetes to v1.15.0-alpha.0

### PR DESCRIPTION
**Pull request by haiyanmeng**

### CODE REVIEW

**Comment by Random-Liu** [comment]
Good, forgot we have alpha releases, that's even better.

/ok-to-test

**Comment by haiyanmeng** [comment]
`/test pull-cri-containerd-verify`

**Comment by mikebrow** [comment]
Hello thanks for the PR. Can you pls sign your commit and force push it back up :-)

**Comment by mikebrow** [comment]
That's a pretty big add lines change, the update is bringing in a repo called structured-merge-diff, might want to skim over that and see if it's inclusion was necessary, and/or how it affects us.

Cheers, Mike

**Comment by haiyanmeng** [comment]
@mikebrow, https://github.com/kubernetes-sigs/structured-merge-diff contains code which implements the Kubernetes "apply" operation, and was merged into the k8s master in https://github.com/kubernetes/kubernetes/pull/72947.

According to the test failure, the pull-cri-containerd-verify and pull-cri-containerd-build error is:
```
I0226 05:30:42.505] vendor/k8s.io/apimachinery/pkg/api/errors/errors.go:30:2:error: cannot find package "sigs.k8s.io/structured-merge-diff/merge" in any of: (vet)
```

**Comment by mikebrow** [comment]
I see...  so when we pick up this commit:  https://github.com/kubernetes/apimachinery/commit/2d0e159c195dcaf4776999fca2e0e37019bf6bc5#diff-d8c7f981f26878f354974019a9484816
we'll loose the structured-merge-diff vndr inclusion.

To sign your commit:

configure git for signing:
git config --global user.name "Full name here"
git config --global user.email "email address here"

Add your signature with -s on each commit:
git commit -s --amend

force push the updated commit:
git push -f origin branch-name


Cheers!

**Comment by haiyanmeng** [comment]
@mikebrow, I updated the k8s dependencies to v1.15.0-alpha.0. Thanks!

**Comment by mikebrow** [comment]
Looking good. 

Now just need to sign the commit using the ^ instructions. And add a second commit (signed :-) that fixes the integration calls to PullImage. See:

integration/addition_gids_test.go:51:36: not enough arguments in call to imageService.PullImage

and other examples in the "make test-integration" results

See

PullImage(image *runtimeapi.ImageSpec, auth *runtimeapi.AuthConfig, **podSandboxConfig *runtimeapi.PodSandboxConfig**) (string, error)

Since podSandboxConfig *runtimeapi.PodSandboxConfig was added above in cri api.. we'll have to add that to our integration tests that call pullimage.

**Comment by haiyanmeng** [comment]
@mikebrow , thanks for pointing out the failed tests. Updated them. PTAL.

I kept using `git commit -S` instead of `git commit -s`, sorry about that!

**Comment by Random-Liu** [comment]
/lgtm

Will wait for @mikebrow 's approval before mering.

**Pull request merged**
