### PR TITLE
Add devices for privileged container

### PR DESCRIPTION
**Pull request by scuzhanglei**
This is a "cherry-pick" of https://github.com/containerd/containerd/pull/5939
Signed-off-by: zhanglei <zhanglei@smartx.com>

### CODE REVIEW

**Review by qiutongs — APPROVED** [review]

**Comment by qiutongs** [comment]
cc @crosbymichael

**Comment by qiutongs** [comment]
The build error doesn't seem to be caused by your change.

**Comment by scuzhanglei** [comment]
hi, any update to this?

**Comment by scuzhanglei** [comment]
ping, thanks

**Comment by scuzhanglei** [comment]
politely ping

**Comment by fengye87** [comment]
The containerd.io package of docker-ce repo is still using 1.4.x versions, so this bug can still affect a lot users. Anything we could help here to make some progress? @qiutongs

**Comment by scuzhanglei** [comment]
@mikebrow @crosbymichael could you please review this cherry-pick PR or give me some feedback, thanks.

**Comment by qiutongs** [comment]
Re @fengye87, just pinged in the containerd-dev slack. Hope this can be merged soon.

**Comment by scuzhanglei** [comment]
ping

**Comment by fuweid** [comment]
Sorry for late reply. I checked that release plan about 1.4. It is in extended status which only received security patch. 

@scuzhanglei 

REF: https://github.com/containerd/containerd/blob/main/RELEASES.md#support-horizon

**Pull request closed without merging**
