### PR TITLE
[release/1.4] vendor: kubernetes v1.19.4

### PR DESCRIPTION
**Pull request by thaJeztah**
relevant changes:

- TLS transport cache: don't cache transports for incomparable configs (https://github.com/kubernetes/kubernetes/pull/95618)

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like CI needs fixing because of the deprecation of `set-env`; https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/

```
Error: Unable to process command '::set-env name=GOPATH::/home/runner/work/cri/cri' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by thaJeztah** [comment]
opened https://github.com/containerd/cri/pull/1607 to fix CI

**Review by mikebrow — APPROVED** [review]
LGTM
on green after rebase .. yada yada

**Comment by thaJeztah** [comment]
rebased 👍 🤞

**Comment by mikebrow** [comment]
e2e failure is not related

**Pull request merged**
