### PR TITLE
Update registry.md for auth config

### PR DESCRIPTION
**Pull request by jdewinne**
I tried using the config `plugins.cri.registry.configs."quay.io".auth` in microk8s, but that didn't work for private registries. However, using `plugins.cri.registry.configs.auth."https://quay.io"` worked for me.
Found this here: https://stackoverflow.com/questions/56642311/microk8s-cannot-pull-from-private-registry

### CODE REVIEW

**Comment by jdewinne** [comment]
I hope this is ok now. I'm not sure why suddenly 2 additional commits are added.

**Comment by mikebrow** [comment]
I think you had staged files? possibly working another commit? 

Squash the last 3 commits:
sudo git rebase --interactive HEAD~3
... select squash to merge the extra commits..
sudo git rebase --continue

**Comment by mikebrow** [comment]
@jdewinne see above comment about rebase squashing...

**Comment by jdewinne** [comment]
Closing this PR in favor of https://github.com/containerd/cri/pull/1375
New laptop, new gpg key, and that caused some craziness with the commits

**Pull request closed without merging**
