### PR TITLE
Switch to containerd/log package

### PR DESCRIPTION
**Pull request by jterry75**
Moves to the containerd/log package over logrus directly. This benefits the
traces because if using any log context such as OpenCensus on the entry gRPC
API all traces for that gRPC method will now contain the appropriate TraceID,
SpanID for easy correlation.

Signed-off-by: Justin Terry (VM) <juterry@microsoft.com>

### CODE REVIEW

**Comment by Random-Liu** [comment]
```
pkg/server/sandbox_portforward.go:52:78:warning: stream can be io.ReadWriter (interfacer)
```

**Comment by Random-Liu** [comment]
LGTM if you did a recursive search in `cmd/`, `pkg/`, `cri.go` and `integration` and didn't find a `logrus` log. :)

**Comment by jterry75** [comment]
@Random-Liu - I dont understand this error. 

This interface is defined here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/portforward/portforward.go#L33

And used here (incorrectly because its `ReadWriteCloser` the caller should not be closing):
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/portforward/httpstream.go#L239

So should the impl of `portForward` call close on the stream? It cant actually be `ReadWriter` without changing the vendor from k8s

**Comment by jterry75** [comment]
Also, its not quite that simple. There are a few `logrus` logs left but all happen on a goroutine not tied to a single context. So I left them alone. For example the "events" server runs in the background and not on a routine.

**Comment by Random-Liu** [comment]
> Also, its not quite that simple. There are a few logrus logs left but all happen on a goroutine not tied to a single context. So I left them alone. For example the "events" server runs in the background and not on a routine.

That seems fine. :)

**Comment by Random-Liu** [comment]
@jterry75 Just change the parameter of `portForward` to `ReadWriter`. :)

**Comment by jterry75** [comment]
@Random-Liu - I get that :). What I am saying is that technically by go "standards" this is incorrect. To pass a `ReadWriteCloser` the caller would `expect` the function to issue the `Close` call. Otherwise it should only have a `ReadWriter`. I can fix it no problem as you said, I'm wondering if we should be calling `Close` here though because k8s seems to have defined the interface as `ReadWriteCloser` for the public API

**Comment by Random-Liu** [comment]
@jterry75 Ha, I get what you mean. :)

Yeah. I'll fix the stream package.

**Comment by Random-Liu** [comment]
@jterry75 https://github.com/kubernetes/kubernetes/pull/80999

**Comment by arman12345678910** [comment]
ReadWriteCloserاز

**Comment by jterry75** [comment]
> @jterry75 Ha, I get what you mean. :)
> 
> Yeah. I'll fix the stream package, but let's do [#1221 (comment)](https://github.com/containerd/cri/pull/1221#issuecomment-518441246) for now here.

Done

**Comment by Random-Liu** [comment]
```
    container_create_test.go:897: TestCase "HostPath should mount as 'rprivate' if propagation is illegal"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x13bc534]
goroutine 23 [running]:
testing.tRunner.func1(0xc000218d00)
	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/testing/testing.go:830 +0x69d
panic(0x1f66400, 0x312b100)
	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/runtime/panic.go:522 +0x1b5
github.com/containerd/cri/vendor/github.com/containerd/containerd/log.GetLogger(0x0, 0x0, 0x9)
	/home/travis/gopath/src/github.com/containerd/cri/vendor/github.com/containerd/containerd/log/context.go:67 +0x34
github.com/containerd/cri/pkg/containerd/opts.WithMounts.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0xc000317800, 0x0, 0x0)
	/home/travis/gopath/src/github.com/containerd/cri/pkg/containerd/opts/spec.go:255 +0xb94
github.com/containerd/cri/pkg/server.TestMountPropagation(0xc000218d00)
	/home/travis/gopath/src/github.com/containerd/cri/pkg/server/container_create_test.go:905 +0x1087
testing.tRunner(0xc000218d00, 0x2160db8)
	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/testing/testing.go:865 +0x164
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/testing/testing.go:916 +0x65b
```

**Comment by jterry75** [comment]
> ```
>     container_create_test.go:897: TestCase "HostPath should mount as 'rprivate' if propagation is illegal"
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x13bc534]
> goroutine 23 [running]:
> testing.tRunner.func1(0xc000218d00)
> 	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/testing/testing.go:830 +0x69d
> panic(0x1f66400, 0x312b100)
> 	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/runtime/panic.go:522 +0x1b5
> github.com/containerd/cri/vendor/github.com/containerd/containerd/log.GetLogger(0x0, 0x0, 0x9)
> 	/home/travis/gopath/src/github.com/containerd/cri/vendor/github.com/containerd/containerd/log/context.go:67 +0x34
> github.com/containerd/cri/pkg/containerd/opts.WithMounts.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0xc000317800, 0x0, 0x0)
> 	/home/travis/gopath/src/github.com/containerd/cri/pkg/containerd/opts/spec.go:255 +0xb94
> github.com/containerd/cri/pkg/server.TestMountPropagation(0xc000218d00)
> 	/home/travis/gopath/src/github.com/containerd/cri/pkg/server/container_create_test.go:905 +0x1087
> testing.tRunner(0xc000218d00, 0x2160db8)
> 	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/testing/testing.go:865 +0x164
> created by testing.(*T).Run
> 	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/testing/testing.go:916 +0x65b
> ```

@Random-Liu - Ha! Fixed, some of the tests pass a nil context which containerd doesnt handle. I just updated them to pass the context but if you want me to fix `containerd/log.GetLog` on a `nil` context I will as well. In this case we want to forward the context anyways for the unified logging.

**Comment by jterry75** [comment]
Thanks!

**Pull request merged**
