### PR TITLE
[release/1.4] Add manifest digest annotation for snapshotters

### PR DESCRIPTION
**Pull request by shahzzzam**
Signed-off-by: Samarth Shah <samarthmshah@gmail.com>

We leverage stargz-based snapshotter and have implemented our own Filesystem interface. We need the image digest to get some metadata for the image itself.

### CODE REVIEW

**Comment by shahzzzam** [comment]
@cpuguy83 @estesp

**Comment by shahzzzam** [comment]
@ktock @cpuguy83 @estesp @thaJeztah  can you help me understand which commits i need to cherry-pick into CRI 1.4 to unblock myself on https://github.com/containerd/containerd/pull/4740

**Comment by ktock** [comment]
Seems you are picking right commits. 57f541b is needed if you want to enable the remote snapshotter without facing the issue of label size limitation (https://github.com/containerd/stargz-snapshotter/issues/144). (but this patch is already merged into the `master` branch of `containerd/containerd`)

**Comment by shahzzzam** [comment]
@ktock I see. @estesp  mentioned https://github.com/containerd/containerd/pull/4740#issuecomment-729295050 [https://github.com/containerd/containerd/pull/4740#issuecomment-729295050](here) that I need this in release/1.4 of CRI first, then vendor it out to containerd `version/1.4`. So we need all the commits related to the change e398fb to go into release/1.4

**Comment by shahzzzam** [comment]
Why is the CI failing?

**Comment by ktock** [comment]
@shahzzzam https://github.com/containerd/cri/pull/1607

**Comment by estesp** [comment]
We should get #1607 merged today and then you can rebase to get a clean CI run.

**Comment by thaJeztah** [comment]
@shahzzzam https://github.com/containerd/cri/pull/1607 was merged, can you try rebasing?

**Comment by shahzzzam** [comment]
Thanks! It's passing the CIs @thaJeztah @estesp

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by estesp — APPROVED** [review]
LGTM

**Pull request merged**
