### PR TITLE
Fix privileged support

### PR DESCRIPTION
**Pull request by Random-Liu**
Fix privileged support.

Signed-off-by: Lantao Liu <lantaol@google.com>

### CODE REVIEW

**Comment by mikebrow** [comment]
https://github.com/containerd/cri/pull/1349#issuecomment-563514786

**Comment by mikebrow** [comment]
> Build execution time has reached the maximum allowed time for your plan (60 minutes).
hmm

**Comment by Random-Liu** [comment]
This seems to be a appveyor issue. Containerd test is fine. Not sure whether it is golang version related. Try to update to 1.13.4 to be the same with containerd.

**Comment by mikebrow** [comment]
> This seems to be a appveyor issue. Containerd test is fine. Not sure whether it is golang version related. Try to update to 1.13.4 to be the same with containerd.

time to move up anyway

**Pull request merged**
