### PR TITLE
Cleanup cri stats integration test

### LINKED ISSUE #400: Cleanup CRI Stats Integration Test
Most of the CRI Stats Integration Tests duplicate the same piece of code.

We should refactor it a little bit with a table driven test.

### PR DESCRIPTION
**Pull request by miaoyq**
Fixes #400

- Clean duplicate codes in cri stats integration test
- Convert the filter tests into table driven tests

@kubernetes-incubator/reviewers-cri-containerd 

Signed-off-by: Yanqiang Miao miao.yanqiang@zte.com.cn

### CODE REVIEW

**Comment by Random-Liu** [comment]
@miaoyq I'll probably review this PR a bit late. :)

**Comment by AkihiroSuda** [comment]
@miaoyq Are you still interested in this?

**Comment by dmcgowan** [comment]
The master branch on this repository has been merged into [containerd/containerd](https://github.com/containerd/containerd). If you are still interested in this change, please rebase your change onto containerd master and open a pull request there.

**Pull request closed without merging**
