### PR TITLE
add introspection service to cri plugin

### PR DESCRIPTION
**Pull request by katiewasnothere**
Related PR: https://github.com/containerd/containerd/pull/3903

Signed-off-by: Kathryn Baldauf <kabaldau@microsoft.com>

### CODE REVIEW

**Comment by katiewasnothere** [comment]
Note: this requires revendoring of containerd on merge of related PR

**Comment by jterry75** [comment]
LGTM

**Comment by jterry75** [comment]
@mikebrow - PTAL, the containerd change went in

**Comment by mikebrow** [comment]
@katiewasnothere we typically do the vendor stuff on a 2nd commit ( should've mentioned that )

**Comment by katiewasnothere** [comment]
> @katiewasnothere we typically do the vendor stuff on a 2nd commit ( should've mentioned that )

Sorry about that, will do in the future :)

**Comment by Random-Liu** [comment]
The change didn't run presubmit...

**Comment by Random-Liu** [comment]
Guess it was fixed by https://github.com/containerd/cri/pull/1368

**Pull request merged**
