### PR TITLE
[release/1.4] bump cni dependencies #1556

### PR DESCRIPTION
**Pull request by mikebrow**
Cherrypick #1556 release 1.4

Signed-off-by: Antonio Ojea <aojea@redhat.com>

### CODE REVIEW

**Comment by mikebrow** [comment]
@aojea FYI

**Comment by aojea** [comment]
> @aojea FYI

thanks, I totally forget about the cherry-pick :sweat:

**Comment by mikebrow** [comment]
> > @aojea FYI
> 
> thanks, I totally forget about the cherry-pick 😓

Oh I meant I'd do it wasn't pushing all the maintainer work on ya :-)

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
